# Generated by Django 5.2.1 on 2025-05-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
